version: "3.9"
services:
  chanchito13:
    build: .
    ports: 
      - "3000:3000" 
    links:
      - mondongodb
  mondongodb:
    image: mongo
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME:denis
      - MONGO_INITDB_ROOT_PASSWORD:password